name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'Feature 🎁'
  - title: '💣 Breaking Change'
    label: 'Breaking Change 💣'
  - title: '🐛 Bug Fixes'
    label: 'Bug 🐛'
  - title: '📝 Documentation'
    label: 'Documentation 📝'
  - title: '🔨 Maintenance'
    label: 'Maintenance 🔨'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## New in CAGEnt v$NEXT_PATCH_VERSION
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch