name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
category-template: '### $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '💣 Breaking Change'
    label: 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🔨 Maintenance'
    label: 'chore'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## New in CAGEnt v$NEXT_PATCH_VERSION
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
