# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ test_workflow ]
  pull_request:
    branches: [ test_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get bundle dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -t Cagent.bundle/Contents/Libraries/Shared/ --no-compile --no-binary=:all -r requirements.txt; fi
        pip install -t Cagent.bundle/Contents/Libraries/Shared/ --no-compile --no-binary=:all requests beautifulsoup4 fuzzywuzzy
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip